name: "SAST: Python Linter using PyAction"
on:
  push:
    branches: [ "main", "workflow" ]
    # paths:
    #   - '**.py'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.py'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: rahul-deepsource/pyaction@1.4.0
        with:
          extra-pylint-options: "--output-format=colorized"
